# Copyright 2026 The EASYDEL / EASYMLX Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Reasoning parsers for MiniMax M2 models.

MiniMax M2 has asymmetric token handling:
- MiniMaxM2ReasoningParser: Treats all content before </think> as reasoning
  (no explicit start token generated by the model).
- MiniMaxM2AppendThinkReasoningParser: Synthetically prepends <think> to output.
"""

from __future__ import annotations

from collections.abc import Sequence

from ...openai_api_modules import DeltaMessage
from ..abstract_reasoning import ReasoningParserManager
from ..basic_parsers import BaseThinkingReasoningParser


@ReasoningParserManager.register_module(["minimax_m2"])
class MiniMaxM2ReasoningParser(BaseThinkingReasoningParser):
    """Asymmetric reasoning parser for MiniMax M2 models.

    MiniMax M2 models do not generate an explicit ``<think>`` start token;
    all content before the ``</think>`` end token is treated as reasoning.
    The ``start_token`` attribute is set for internal logic but is never
    emitted by the model itself.

    Attributes:
        start_token (str): The ``<think>`` tag used for internal logic
            (not generated by the model).
        end_token (str): The ``</think>`` tag that marks the end of
            reasoning content.

    Example:
        >>> parser = MiniMaxM2ReasoningParser()
        >>> reasoning, content = parser.extract_reasoning(
        ...     "some reasoning</think>final answer"
        ... )
        >>> reasoning
        'some reasoning'
        >>> content
        'final answer'
    """

    start_token = "<think>"
    end_token = "</think>"

    def extract_reasoning(self, model_output: str, request=None) -> tuple[str | None, str | None]:
        """Extract reasoning content by splitting at the ``</think>`` token.

        Everything before the end token is treated as reasoning, regardless
        of whether the start token is present. If no end token is found,
        the entire output is returned as content (unless a start token is
        present, in which case the cleaned output is returned as reasoning).

        Args:
            model_output (str): The raw model output string to parse.
            request: Optional request context (unused in this parser).

        Returns:
            tuple[str | None, str | None]: A two-element tuple of
                ``(reasoning, content)``. Either element may be ``None``
                if the corresponding portion is empty or absent.
        """
        if self.end_token not in model_output:
            if self.start_token in model_output:
                cleaned = model_output.replace(self.start_token, "").strip()
                return cleaned or None, None
            return None, model_output
        parts = model_output.split(self.end_token, 1)
        reasoning = parts[0].replace(self.start_token, "").strip()
        content = parts[1].strip() if len(parts) > 1 else None
        return reasoning or None, content

    def extract_reasoning_streaming(
        self,
        previous_text: str,
        current_text: str,
        delta_text: str,
        previous_token_ids: Sequence[int],
        current_token_ids: Sequence[int],
        delta_token_ids: Sequence[int],
        request=None,
    ) -> DeltaMessage | None:
        """Extract reasoning content incrementally during streaming.

        All text before the ``</think>`` token is emitted as
        ``reasoning_content``; everything after is emitted as ``content``.
        If the delta itself contains the end token, the delta is split
        accordingly.

        Args:
            previous_text (str): Text accumulated before this chunk.
            current_text (str): Full text including the current chunk.
            delta_text (str): New text in the current chunk.
            previous_token_ids (Sequence[int]): Token IDs up to the
                previous chunk.
            current_token_ids (Sequence[int]): All token IDs so far.
            delta_token_ids (Sequence[int]): New token IDs in this chunk.
            request: Optional request context (unused).

        Returns:
            DeltaMessage | None: A delta containing either
                ``reasoning_content``, ``content``, or both if the end
                token appears in this delta. Returns ``None`` if the
                delta is empty.
        """
        if not delta_text:
            return None

        has_end_in_prev = self.end_token in previous_text
        has_end_in_delta = self.end_token in delta_text

        if has_end_in_prev:
            return DeltaMessage(content=delta_text)

        if has_end_in_delta:
            parts = delta_text.split(self.end_token, 1)
            reasoning_part = parts[0].replace(self.start_token, "")
            content_part = parts[1] if len(parts) > 1 else None
            return DeltaMessage(
                reasoning_content=reasoning_part if reasoning_part else None,
                content=content_part if content_part else None,
            )

        cleaned = delta_text.replace(self.start_token, "")
        return DeltaMessage(reasoning_content=cleaned) if cleaned else None


@ReasoningParserManager.register_module(["minimax_m2_append_think"])
class MiniMaxM2AppendThinkReasoningParser(BaseThinkingReasoningParser):
    """Reasoning parser that synthetically prepends ``<think>`` to output.

    Some MiniMax configurations do not emit the ``<think>`` start token.
    This parser prepends it before delegating to the base
    ``BaseThinkingReasoningParser`` so that the standard symmetric
    extraction logic can be reused.

    Attributes:
        start_token (str): The ``<think>`` tag prepended if missing.
        end_token (str): The ``</think>`` tag marking reasoning end.

    Example:
        >>> parser = MiniMaxM2AppendThinkReasoningParser()
        >>> reasoning, content = parser.extract_reasoning(
        ...     "reasoning here</think>answer"
        ... )
        >>> reasoning
        'reasoning here'
    """

    start_token = "<think>"
    end_token = "</think>"

    def extract_reasoning(self, model_output: str, request=None) -> tuple[str | None, str | None]:
        """Prepend ``<think>`` if missing, then delegate to the base parser.

        Args:
            model_output (str): The raw model output string.
            request: Optional request context (unused).

        Returns:
            tuple[str | None, str | None]: A two-element tuple of
                ``(reasoning, content)`` as returned by the base class.
        """
        if self.start_token not in model_output:
            model_output = self.start_token + model_output
        return super().extract_reasoning(model_output, request)
