# Copyright 2026 The EASYDEL / EASYMLX Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Reasoning parser for Step3 models.

Step3 uses only the </think> end token (no explicit start token).
All content before </think> is treated as reasoning.
"""

from __future__ import annotations

from collections.abc import Sequence

from ...openai_api_modules import DeltaMessage
from ..abstract_reasoning import ReasoningParserManager
from ..basic_parsers import BaseThinkingReasoningParser


@ReasoningParserManager.register_module(["step3"])
class Step3ReasoningParser(BaseThinkingReasoningParser):
    """Reasoning parser for Step3 models with asymmetric token handling.

    Step3 models generate only the ``</think>`` end token; they do not
    emit an explicit ``<think>`` start token. All content before the
    first ``</think>`` is treated as reasoning, and everything after is
    treated as visible content.

    Attributes:
        start_token (str): The ``<think>`` tag (used internally for
            cleanup but not generated by the model).
        end_token (str): The ``</think>`` tag that the model generates
            to mark the boundary between reasoning and content.

    Example:
        >>> parser = Step3ReasoningParser()
        >>> reasoning, content = parser.extract_reasoning(
        ...     "internal reasoning</think>public answer"
        ... )
        >>> reasoning
        'internal reasoning'
        >>> content
        'public answer'
    """

    start_token = "<think>"
    end_token = "</think>"

    def extract_reasoning(self, model_output: str, request=None) -> tuple[str | None, str | None]:
        """Extract reasoning by splitting at the ``</think>`` token.

        All text before the end token is reasoning. If the start token
        is present it is stripped from the reasoning text. If no end
        token is found and a start token is present, the cleaned text
        is returned as reasoning with no content.

        Args:
            model_output (str): The raw model output string.
            request: Optional request context (unused).

        Returns:
            tuple[str | None, str | None]: A two-element tuple of
                ``(reasoning, content)``.
        """
        if self.end_token not in model_output:
            if self.start_token in model_output:
                cleaned = model_output.replace(self.start_token, "").strip()
                return cleaned or None, None
            return None, model_output
        parts = model_output.split(self.end_token, 1)
        reasoning = parts[0].replace(self.start_token, "").strip()
        content = parts[1].strip() if len(parts) > 1 else None
        return reasoning or None, content

    def extract_reasoning_streaming(
        self,
        previous_text: str,
        current_text: str,
        delta_text: str,
        previous_token_ids: Sequence[int],
        current_token_ids: Sequence[int],
        delta_token_ids: Sequence[int],
        request=None,
    ) -> DeltaMessage | None:
        """Extract reasoning content incrementally during streaming.

        Emits all text as ``reasoning_content`` until the ``</think>``
        end token is encountered, then switches to emitting ``content``.
        If the end token appears within the current delta, the delta is
        split into reasoning and content parts.

        Args:
            previous_text (str): Text accumulated before this chunk.
            current_text (str): Full text including the current chunk.
            delta_text (str): New text in the current chunk.
            previous_token_ids (Sequence[int]): Token IDs up to the
                previous chunk.
            current_token_ids (Sequence[int]): All token IDs so far.
            delta_token_ids (Sequence[int]): New token IDs in this chunk.
            request: Optional request context (unused).

        Returns:
            DeltaMessage | None: A delta containing ``reasoning_content``
                before the end token and/or ``content`` after. Returns
                ``None`` if the delta is empty.
        """
        if not delta_text:
            return None

        if self.end_token in previous_text:
            return DeltaMessage(content=delta_text)

        if self.end_token in delta_text:
            parts = delta_text.split(self.end_token, 1)
            reasoning_part = parts[0].replace(self.start_token, "")
            content_part = parts[1] if len(parts) > 1 else None
            return DeltaMessage(
                reasoning_content=reasoning_part if reasoning_part else None,
                content=content_part if content_part else None,
            )

        cleaned = delta_text.replace(self.start_token, "")
        return DeltaMessage(reasoning_content=cleaned) if cleaned else None
